version: '3.7'
services:
  backend:
    restart: always
    volumes:
      - /var/www/jakob.wtf:/var/www
    init: true
    image: jakob-wtf-backend:latest
    secrets:
      - auth
      - log_lvl
      - db_db
      - db_pass
      - db_user
      - db_port
      - db_host
    environment:
      NODE_ENV: production
  frontend:
    restart: always
    init: true
    image: jakob-wtf-frontend:latest
    secrets:
      - auth
    environment:
      NODE_ENV: production
  jakob-reverse-proxy:
    restart: always
    init: true
    image: jakob-wtf-proxy:latest
    depends_on:
      - backend
      - frontend
    volumes:
      - /var/www/jakob.wtf:/var/www
    networks:
      - jakob-proxy
      - default
secrets:
  auth:
    file: /opt/secrets/auth
  db_db:
    file: /opt/secrets/db_db
  db_host:
    file: /opt/secrets/db_host
  db_pass:
    file: /opt/secrets/db_pass
  db_port:
    file: /opt/secrets/db_port
  db_user:
    file: /opt/secrets/db_user
  log_lvl:
    file: /opt/secrets/log_lvl

networks:
  jakob-proxy:
    name: jakob-proxy




    

