version: '3.7'
services:
  backend:
    restart: always
    depends_on:
      - db
    init: true
    image: jakob-wtf-backend:latest
    secrets:
      - auth
      - log_lvl
      - db
  frontend:
    restart: always
    init: true
    image: jakob-wtf-frontend:latest
    secrets:
      - auth
  db:
    restart: always
    init: true
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - /srv/data/maria:/var/lib/mysql
      - /home/docker/maria/my.cnf:/etc/mysql/my.cnf
    ports:
      - 50000:3306
  reverse-proxy:
    restart: always
    init: true
    image: jakob-wtf-proxy:latest
    depends_on:
      - backend
      - frontend
    volumes:
      - /var/www/jakob.wtf:/var/www
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "80:80"
      - "443:443"



    

