# This is a basic workflow that is manually triggered

name: Jakob.wtf Frontend Deployment

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  upload:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build Docker Image
      uses: docker/build-push-action@v3
      with:
        context: frontend
        load: true
        tags: jakob-wtf-frontend:latest
    - name: Save to Archive
      run: |
        docker image save -o deployment/jakob-wtf-frontend.tar jakob-wtf-frontend:latest
    - name: Deploy to Server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "deployment/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
